// Code generated by Prismic. DO NOT EDIT.

import Boxes from "./boxes";
import BrandPromo from "./BrandPromo";
import ClinicComparison from "./clinic_comparison";
import Divider from "./divider";
import Hero from "./hero";
import Posts from "./posts";
import Quote from "./quote";
import Ribbon from "./Ribbon";
import SideBySide from "./side_by_side";
import StartHere from "./start_here";

export const components = {
  boxes: Boxes,
  brand_promo: BrandPromo,
  clinic_comparison: ClinicComparison,
  divider: Divider,
  hero: Hero,
  posts: Posts,
  quote: Quote,
  ribbon: Ribbon,
  side_by_side: SideBySide,
  start_here: StartHere,
};
