// Code generated by Prismic. DO NOT EDIT.

import ClinicComparison from "./clinic_comparison";
import Divider from "./divider";
import Hero from "./hero";
import Quote from "./quote";
import Posts from "./posts";
import SideBySide from "./side_by_side";
import StartHere from "./start_here";

export const components = {
  clinic_comparison: ClinicComparison,
  divider: Divider,
  hero: Hero,
  quote: Quote,
  posts: Posts,
  side_by_side: SideBySide,
  start_here: StartHere,
};
